- hosts: elastic
  become: yes
  gather_facts: true
  tasks:

  - name: install elastic
    apt:
      deb: "https://mirror.yandex.ru/mirrors/elastic/7/pool/main/e/elasticsearch/elasticsearch-7.5.0-amd64.deb"

  - name: copy elasticsearch config file
    copy:
      src: elasticsearch.yml
      dest: /etc/elasticsearch/elasticsearch.yml

  - name: Make sure a service is running
    systemd:
      state: started
      name: elasticsearch
